services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: marketing_request_app
    ports:
      - "8084:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - marketing-network

  db:
    image: mysql:8.0
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: marketing_request
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - marketing-network

networks:
  marketing-network:
    driver: bridge

volumes:
  db_data:
